import { Component, OnInit, ViewChild, OnDestroy } from '@angular/core';
import { FormGroup, FormBuilder, FormControl } from '@angular/forms';
import { Subscription } from 'rxjs';

/**
 * Display a user search form with a resulting user list
 */
@Component({
  selector: 'app-user-search',
  templateUrl: './user-search.component.html',
  styleUrls: ['./user-search.component.scss']
})
export class UserSearchComponent implements OnInit, OnDestroy {
  // reference to set focus on this field
  @ViewChild('search', { static: true })
  search: any;

  /**
   * params generated by the search form to send to app-user-list
   */
  public params: any | null = null;

  /**
   * list of attributes that can be searched
   * ::TODO:: make this a configuration, adding optional fields as needed
   */
  public attributes: any[] = [
    {
      value: 'email',
      label: 'Email'
    },
    {
      value: 'status',
      label: 'Enabled',
      options: [
        'Enabled',
        'Disabled'
      ]
    },
    {
      value: 'family_name',
      label: 'Family Name'
    },
    {
      value: 'given_name',
      label: 'Given Name'
    },
    {
      value: 'name',
      label: 'Name'
    },
    {
      value: 'phone_number',
      label: 'Phone Number'
    },

    {
      value: 'preferred_username',
      label: 'Preferred Name'
    },
    {
      value: 'cognito:user_status',
      label: 'Status',
      options: [
        'UNCONFIRMED',
        'CONFIRMED',
        'ARCHIVED',
        'COMPROMISED',
        'UNKNOWN',
        'RESET_REQUIRED',
        'FORCE_CHANGE_PASSWORD'
      ]
    },
    {
      value: 'sub',
      label: 'Sub'
    },
    {
      value: 'username',
      label: 'Username'
    }
  ];

  /**
   * Types of searchs available
   */
  public types: any[] = [
    {
      value: '=',
      label: 'Equals'
    }, {
      value: '^=',
      label: 'Starts with'
    }
  ];

  /**
   * Default search parameters
   */
  private formDefaults: any = {
    search: '',
    attribute: 'email',
    type: '^='
  };

  public typeOptions: any[] = [];

  /**
   * Search form
   */
  public form: FormGroup = new FormBuilder().group({
    searchFormControl: new FormControl(this.formDefaults.search),
    attributeFormControl: new FormControl(this.formDefaults.attribute),
    typeFormControl: new FormControl(this.formDefaults.type)
  });

  /**
   * Reference to later unsubscribe
   */
  private attributeSubscription?: Subscription;

  /**
   * Based on selected attribute return the available options
   */
  public setSearchOptions(type: string) {
    // find the attribute
    const found = this.attributes.find(element => element.value === type);
    if (found) {
      this.typeOptions = found.options;
      return found.Value;
    } else {
      this.typeOptions = [];
    }
  }

  /**
   * Handle submiting
   */
  public submit() {
    let parameters = {};
    const searchData = this.form.getRawValue();
    const filter = searchData.attributeFormControl +
      ' ' +
      searchData.typeFormControl +
      ' ' +
      '\"' +
      searchData.searchFormControl +
      '\"';
    parameters = {
      Filter: filter
    };
    // pass parameters to the template
    this.params = parameters;
  }

  /**
   * Clear
   */
  public clear() {
    this.form.reset(
      {
        searchFormControl: this.formDefaults.search,
        attributeFormControl: this.formDefaults.attribute,
        typeFormControl: this.formDefaults.type
      }
    );
    this.submit();
  }

  /**
   * Handles when the component is first created
   */
  ngOnInit() {
    // focus on search input
    setTimeout(() => {
      this.search.nativeElement.focus();
    }, 1);
    // perform default search
    this.submit();
    // setup a subscription to update the search options when the attribute updates
    this.attributeSubscription = this.form.controls.attributeFormControl.valueChanges.subscribe(
      type => {
        this.setSearchOptions(type);
      }
    );
  }

  /**
   * Handle when the component is destroyed
   */
  public ngOnDestroy(): void {
    if (this.attributeSubscription) {
      this.attributeSubscription.unsubscribe();
    }
  }

}
